import { auth, db } from './firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { collection, onSnapshot } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $ = (id) => document.getElementById(id); let stopDoctors;
onAuthStateChanged(auth, (user) => { if (!user) return window.location.replace('index.html'); $('userEmail').textContent = user.email || 'Signed in'; if (stopDoctors) stopDoctors(); stopDoctors = onSnapshot(collection(db, 'users', user.uid, 'doctors'), (snapshot) => renderDoctors(snapshot.docs), (error) => showMessage(error.code === 'permission-denied' ? 'Permission denied. Your account cannot view these doctors.' : 'Could not load doctors. Check your internet connection.', true)); });
function esc(value = '') { const d = document.createElement('div'); d.textContent = value; return d.innerHTML; }
function renderDoctors(docs) { const grid = $('doctorGrid'); if (!docs.length) { grid.innerHTML = '<div class="empty-state"><div>+</div><h2>No doctors yet</h2><p>Add doctors from the MediQueue Android app to see them here.</p></div>'; return; } grid.innerHTML = docs.map((doc) => { const d = doc.data(), name = d.doctorName || 'Doctor', initial = esc(name.charAt(0)); const photo = d.photo ? `<img src="${esc(d.photo)}" alt="${esc(name)}" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover" onerror="this.remove()">` : ''; return `<article class="doctor-card"><div class="doctor-photo" style="position:relative">${photo}<span>${initial}</span></div><div class="doctor-card-body"><p class="doctor-specialty">${esc(d.specialization || 'General Medicine')}</p><h2>${esc(name)}</h2><p class="room-label">Room <strong>${esc(d.roomNo || '—')}</strong></p><div class="card-serial"><span>Current serial</span><strong>${esc(d.currentSerial ?? '—')}</strong></div><a class="display-link" href="display.html">Open display <span>→</span></a></div></article>`; }).join(''); $('dashboardMessage').hidden = true; }
function showMessage(text, isError = false) { const message = $('dashboardMessage'); message.textContent = text; message.className = `dashboard-message ${isError ? 'error' : ''}`; message.hidden = false; $('doctorGrid').innerHTML = ''; }
$('logoutButton').addEventListener('click', async () => { try { await signOut(auth); } catch { showToast('Unable to log out. Please try again.'); } });
function showToast(text) { const toast = $('toast'); toast.textContent = text; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3500); }
