import { auth, db } from './firebase.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { doc, onSnapshot } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $ = (id) => document.getElementById(id); const doctorId = new URLSearchParams(location.search).get('id'); let unsubscribe, lastSerial, lastPatient;
if (!doctorId) showError('Doctor not selected', 'Open a doctor display from the dashboard.');
onAuthStateChanged(auth, (user) => { if (!user) return location.replace('index.html'); if (doctorId) subscribe(user.uid); });
function subscribe(uid) { if (unsubscribe) unsubscribe(); setConnection('connecting', 'Connecting…'); unsubscribe = onSnapshot(doc(db, 'users', uid, 'doctors', doctorId), { includeMetadataChanges: true }, (snap) => { if (!snap.exists()) return showError('Doctor not found', 'This doctor may have been removed.'); const d = snap.data(); update(d); $('displayLoading').hidden = true; $('displayApp').hidden = false; setConnection(snap.metadata.fromCache ? 'offline' : 'connected', snap.metadata.fromCache ? 'Offline — showing saved data' : 'Realtime Firestore connected'); }, (error) => showError(error.code === 'permission-denied' ? 'Permission denied' : 'Firestore connection error', error.code === 'permission-denied' ? 'You do not have access to this doctor display.' : 'Please check your internet connection and try again.')); }
function update(d) { $('doctorName').textContent = d.doctorName || 'Doctor'; $('doctorSpecialization').textContent = d.specialization || 'General Medicine'; $('roomNumber').textContent = `Room ${d.roomNo || '—'}`; $('hospitalName').textContent = d.chamberName || 'MEDIQUEUE HOSPITAL'; const serial = d.currentSerial ?? '—', patient = d.nowServingName || 'Waiting for the next patient'; const serialEl = $('serialNumber'), patientEl = $('patientName'); if (lastSerial !== undefined && serial !== lastSerial) animate(serialEl, 'serial-changed'); if (lastPatient !== undefined && patient !== lastPatient) animate(patientEl, 'patient-changed'); serialEl.textContent = serial; patientEl.textContent = patient; lastSerial = serial; lastPatient = patient; }
function animate(el, className) { el.classList.remove(className); void el.offsetWidth; el.classList.add(className); }
function setConnection(status, text) { const badge = $('connectionBadge'); badge.className = `connection-badge ${status}`; badge.querySelector('span').textContent = text; }
function showError(title, text) { $('displayLoading').hidden = true; $('displayApp').hidden = true; $('displayError').hidden = false; $('errorTitle').textContent = title; $('errorText').textContent = text; }
function updateClock() { const now = new Date(); $('currentTime').textContent = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }); $('currentDate').textContent = now.toLocaleDateString([], { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }); } updateClock(); setInterval(updateClock, 1000);
async function toggleFullscreen() { try { if (!document.fullscreenElement) await document.documentElement.requestFullscreen(); else await document.exitFullscreen(); } catch {} } $('fullscreenButton').addEventListener('click', toggleFullscreen); document.addEventListener('keydown', (e) => { if (e.key.toLowerCase() === 'f' && !['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)) { e.preventDefault(); toggleFullscreen(); } }); window.addEventListener('online', () => setConnection('connecting', 'Reconnecting…')); window.addEventListener('offline', () => setConnection('offline', 'Offline — waiting to reconnect')); $('retryButton').addEventListener('click', () => location.reload());
