import { auth, db } from './firebase.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { collection, doc, onSnapshot } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $ = (id) => document.getElementById(id); let doctorId = ''; let unsubscribe, doctorListUnsubscribe, lastSerial, lastPatient, doctorsLoaded = false, currentUserId = '';
onAuthStateChanged(auth, (user) => { if (!user) return window.location.replace('index.html'); currentUserId = user.uid; loadDoctors(user.uid); });
function loadDoctors(uid) { doctorsLoaded = false; if (doctorListUnsubscribe) doctorListUnsubscribe(); const timeout = setTimeout(() => { if (!doctorsLoaded) showError('Firestore did not respond', 'No response after 4 seconds. Check internet, Firebase project configuration, and Firestore Rules.'); }, 4000); doctorListUnsubscribe = onSnapshot(collection(db, 'users', uid, 'doctors'), (doctors) => { doctorsLoaded = true; clearTimeout(timeout); const select = $('doctorSelect'), selectedId = doctorId || select.value; select.innerHTML = '<option value="">Select doctor…</option>'; if (doctors.empty) return showError('No doctors found', `No doctors exist under users/${uid}/doctors. Log in using the same Firebase account as the Android app.`); doctors.forEach((doctor) => { const data = doctor.data(), option = document.createElement('option'); option.value = doctor.id; option.textContent = `${data.doctorName || data.name || 'Doctor'}${data.roomNo ? ` — Room ${data.roomNo}` : ''}`; option.selected = doctor.id === selectedId; select.append(option); }); $('displayLoading').hidden = true; $('displayError').hidden = true; $('displayApp').hidden = false; if (doctorId) subscribe(uid, doctorId); else setConnection('connecting', 'Select a doctor to connect'); }, (error) => { clearTimeout(timeout); showError('Firestore error', `${error.code || 'unknown-error'}: ${error.message || 'Unable to load doctors.'}`); }); }
function subscribe(uid, id) { if (unsubscribe) unsubscribe(); setConnection('connecting', 'Connecting…'); unsubscribe = onSnapshot(doc(db, 'users', uid, 'doctors', id), { includeMetadataChanges: true }, (snap) => { if (!snap.exists()) return showError('Doctor not found', 'This doctor may have been removed.'); const d = snap.data(); update(d); $('displayLoading').hidden = true; $('displayApp').hidden = false; setConnection(snap.metadata.fromCache ? 'offline' : 'connected', snap.metadata.fromCache ? 'Offline — showing saved data' : 'Realtime Firestore connected'); }, (error) => showError('Firestore connection error', `${error.code || 'unknown-error'}: ${error.message || 'Unable to load this doctor.'}`)); }
function update(d) { $('doctorName').textContent = d.doctorName || d.name || 'Doctor'; $('doctorSpecialization').textContent = d.specialization || d.department || 'General Medicine'; $('roomNumber').textContent = `Room ${d.roomNo || d.room || '—'}`; $('hospitalName').textContent = d.chamberName || 'MEDIQUEUE HOSPITAL'; const serial = d.currentSerial ?? d.nowServing ?? '—', patient = d.nowServingName || d.patientName || (d.nowServing != null ? `Token ${d.nowServing}` : 'Waiting for the next patient'); const serialEl = $('serialNumber'), patientEl = $('patientName'); if (lastSerial !== undefined && serial !== lastSerial) animate(serialEl, 'serial-changed'); if (lastPatient !== undefined && patient !== lastPatient) animate(patientEl, 'patient-changed'); serialEl.textContent = serial; patientEl.textContent = patient; lastSerial = serial; lastPatient = patient; }
function animate(el, className) { el.classList.remove(className); void el.offsetWidth; el.classList.add(className); }
function setConnection(status, text) { const badge = $('connectionBadge'); badge.className = `connection-badge ${status}`; badge.querySelector('span').textContent = text; }
function showError(title, text) { $('displayLoading').hidden = true; $('displayApp').hidden = true; $('displayError').hidden = false; $('errorTitle').textContent = title; $('errorText').textContent = text; }
function updateClock() { const now = new Date(); $('currentTime').textContent = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }); $('currentDate').textContent = now.toLocaleDateString([], { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }); } updateClock(); setInterval(updateClock, 1000);
async function toggleFullscreen() { try { if (!document.fullscreenElement) await document.documentElement.requestFullscreen(); else await document.exitFullscreen(); } catch {} } $('fullscreenButton').addEventListener('click', toggleFullscreen); document.addEventListener('keydown', (e) => { if (e.key.toLowerCase() === 'f' && !['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)) { e.preventDefault(); toggleFullscreen(); } }); window.addEventListener('online', () => setConnection('connecting', 'Reconnecting…')); window.addEventListener('offline', () => setConnection('offline', 'Offline — waiting to reconnect')); $('retryButton').addEventListener('click', () => location.reload());
$('doctorSelect').addEventListener('change', (event) => { doctorId = event.target.value; if (!doctorId || !currentUserId) return; lastSerial = undefined; lastPatient = undefined; subscribe(currentUserId, doctorId); });
